### PR TITLE
emsdp: modify document

### PR DESCRIPTION
**Pull request by vonhust**
Modify package info

Use em11d as example in document

fix document url

Signed-off-by: Yuguo Zou <yuguo.zou@synopsys.com>

# Summary
- Summarize the main changes or features of your pull request.
- Describe the development status of your pull request.
- List all the related issues of your pull request.

# ToDos
- [] Todo list 1
- [] Todo list 2

# User Manual
Describe about how to test or reproduce the new features or bugs fixed of your pull request.

### CODE REVIEW

**Comment by fanghuaqi** [comment]
# Sphinx link check result 
***********************
<pre>contribute/CONTRIBUTING.md:35: [local] CODE_OF_CONDUCT.html<br>contribute/CONTRIBUTING.md:101: [local] ISSUE_TEMPLATE.html<br>contribute/CONTRIBUTING.md:129: [local] ISSUE_TEMPLATE.html<br>contribute/CONTRIBUTING.md:220: [broken] https://github.com/atom/atom/blob/master/CONTRIBUTING: 404 Client Error: Not Found for url: https://github.com/atom/atom/blob/master/CONTRIBUTING<br>example/example/baremetal/openthread/cli/OT_CLI.md:1732: [local] ./OT_DIAG.html<br>getting_started/hardware_requirement.rst:38: [broken] http://www.solomon-systech.com/en/product/display-ic/oled-driver-controller/ssd1306/: 403 Client Error: Forbidden for url: http://www.solomon-systech.com/en/product/display-ic/oled-driver-controller/ssd1306/<br>getting_started/peripheral_preparation.rst:77: [redirected permanently] http://wiki.ai-thinker.com/esp8266/docs to https://wiki.ai-thinker.com/esp8266/docs<br>getting_started/peripheral_preparation.rst:80: [redirected permanently] http://wiki.ai-thinker.com/esp8266/docs to https://wiki.ai-thinker.com/esp8266/docs<br>license/license.rst:102: [broken] http://elm-chan.org/: 403 Client Error: Forbidden for url: http://elm-chan.org/<br>license/license.rst:101: [broken] http://elm-chan.org/fsw/ff/00index_e.html: 403 Client Error: Forbidden for url: http://elm-chan.org/fsw/ff/00index_e.html<br>license/license.rst:275: [broken] http://elm-chan.org/fsw/strf/xprintf.html: 403 Client Error: Forbidden for url: http://elm-chan.org/fsw/strf/xprintf.html<br></pre>

**Comment by YuguoWH** [comment]
Warning: by removing EMSDP default core config files (em11d_dfss), current CI would fail.

**Comment by fanghuaqi** [comment]
# Sphinx link check result 
***********************
<pre>contribute/CONTRIBUTING.md:35: [local] CODE_OF_CONDUCT.html<br>contribute/CONTRIBUTING.md:101: [local] ISSUE_TEMPLATE.html<br>contribute/CONTRIBUTING.md:129: [local] ISSUE_TEMPLATE.html<br>contribute/CONTRIBUTING.md:220: [broken] https://github.com/atom/atom/blob/master/CONTRIBUTING: 404 Client Error: Not Found for url: https://github.com/atom/atom/blob/master/CONTRIBUTING<br>example/example/baremetal/openthread/cli/OT_CLI.md:1732: [local] ./OT_DIAG.html<br>getting_started/hardware_requirement.rst:38: [broken] http://www.solomon-systech.com/en/product/display-ic/oled-driver-controller/ssd1306/: 403 Client Error: Forbidden for url: http://www.solomon-systech.com/en/product/display-ic/oled-driver-controller/ssd1306/<br>license/license.rst:102: [broken] http://elm-chan.org/: 403 Client Error: Forbidden for url: http://elm-chan.org/<br>license/license.rst:101: [broken] http://elm-chan.org/fsw/ff/00index_e.html: 403 Client Error: Forbidden for url: http://elm-chan.org/fsw/ff/00index_e.html<br>license/license.rst:275: [broken] http://elm-chan.org/fsw/strf/xprintf.html: 403 Client Error: Forbidden for url: http://elm-chan.org/fsw/strf/xprintf.html<br></pre>

**Comment by fanghuaqi** [comment]
# Sphinx link check result 
***********************
<pre>contribute/CONTRIBUTING.md:35: [local] CODE_OF_CONDUCT.html<br>contribute/CONTRIBUTING.md:101: [local] ISSUE_TEMPLATE.html<br>contribute/CONTRIBUTING.md:129: [local] ISSUE_TEMPLATE.html<br>contribute/CONTRIBUTING.md:220: [broken] https://github.com/atom/atom/blob/master/CONTRIBUTING: 404 Client Error: Not Found for url: https://github.com/atom/atom/blob/master/CONTRIBUTING<br>example/example/baremetal/openthread/cli/OT_CLI.md:1732: [local] ./OT_DIAG.html<br>getting_started/hardware_requirement.rst:38: [broken] http://www.solomon-systech.com/en/product/display-ic/oled-driver-controller/ssd1306/: 403 Client Error: Forbidden for url: http://www.solomon-systech.com/en/product/display-ic/oled-driver-controller/ssd1306/<br>license/license.rst:102: [broken] http://elm-chan.org/: 403 Client Error: Forbidden for url: http://elm-chan.org/<br>license/license.rst:101: [broken] http://elm-chan.org/fsw/ff/00index_e.html: 403 Client Error: Forbidden for url: http://elm-chan.org/fsw/ff/00index_e.html<br>license/license.rst:275: [broken] http://elm-chan.org/fsw/strf/xprintf.html: 403 Client Error: Forbidden for url: http://elm-chan.org/fsw/strf/xprintf.html<br></pre>

**Comment by fanghuaqi** [comment]
# Sphinx link check result 
***********************
<pre>contribute/CONTRIBUTING.md:35: [local] CODE_OF_CONDUCT.html<br>contribute/CONTRIBUTING.md:101: [local] ISSUE_TEMPLATE.html<br>contribute/CONTRIBUTING.md:129: [local] ISSUE_TEMPLATE.html<br>contribute/CONTRIBUTING.md:220: [broken] https://github.com/atom/atom/blob/master/CONTRIBUTING: 404 Client Error: Not Found for url: https://github.com/atom/atom/blob/master/CONTRIBUTING<br>example/example/baremetal/openthread/cli/OT_CLI.md:1732: [local] ./OT_DIAG.html<br>getting_started/hardware_requirement.rst:38: [broken] http://www.solomon-systech.com/en/product/display-ic/oled-driver-controller/ssd1306/: 403 Client Error: Forbidden for url: http://www.solomon-systech.com/en/product/display-ic/oled-driver-controller/ssd1306/<br>license/license.rst:102: [broken] http://elm-chan.org/: 403 Client Error: Forbidden for url: http://elm-chan.org/<br>license/license.rst:101: [broken] http://elm-chan.org/fsw/ff/00index_e.html: 403 Client Error: Forbidden for url: http://elm-chan.org/fsw/ff/00index_e.html<br>license/license.rst:275: [broken] http://elm-chan.org/fsw/strf/xprintf.html: 403 Client Error: Forbidden for url: http://elm-chan.org/fsw/strf/xprintf.html<br></pre>

**Pull request merged**
